### ISSUE TITLE
\newread 

### ISSUE THREAD

**Issue by davidcarlisle** [opieters/DynamicNumber#1]
Hi Just noticed this package via tlmgr;-)

Currently it does a `\newread` for every file load, as there are only 16 of these that's a bit expensive of tex resources.

Since the stream is opened and closed each time they can all use the same stream so `\newread\ccinstream` could usefully be moved to the top level (a side point it could use the same `dn` prefix as the other csnames defined by the package:-)

**Comment by opieters** [comment]
Hi

Thanks for the feedback, I appreciate it!

It should now be fixed. The naming convention is a remnant from another package (not yet on CTAN) I created :)
